"""
Utility functions for ClaraVision Health
PDF generation and email functionality
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from datetime import datetime
import io
import os
from PIL import Image as PILImage
from disease_database import DISEASE_DATABASE
try:
    from disease_database import get_disease_info
except ImportError:
    def get_disease_info(class_name):
        if class_name in DISEASE_DATABASE:
            return DISEASE_DATABASE[class_name]
        class_lower = class_name.lower()
        if class_lower in DISEASE_DATABASE:
            return DISEASE_DATABASE[class_lower]
        class_underscore = class_name.replace(' ', '_')
        if class_underscore in DISEASE_DATABASE:
            return DISEASE_DATABASE[class_underscore]
        class_no_underscore = class_name.replace('_', ' ')
        if class_no_underscore in DISEASE_DATABASE:
            return DISEASE_DATABASE[class_no_underscore]
        class_title = class_name.title()
        if class_title in DISEASE_DATABASE:
            return DISEASE_DATABASE[class_title]
        return None
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

def generate_pdf_report(results, image, timestamp, include_treatment=True, include_prevention=True, include_when_to_seek_care=True):
    """
    Generate a professional PDF report of the skin condition analysis
    
    Args:
        results: API response from Roboflow
        image: PIL Image object
        timestamp: datetime object
        include_treatment: bool
        include_prevention: bool
        include_when_to_seek_care: bool
    
    Returns:
        str: Path to generated PDF file
    """
    
    # Create filename
    filename = f"claravision_report_{timestamp.strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join("/home/claude", filename)
    
    # Create PDF document
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=1*inch,
        bottomMargin=0.75*inch
    )
    
    # Container for PDF elements
    story = []
    
    # Define custom styles
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e3a8a'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    # Subtitle style
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=12,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=20,
        alignment=TA_CENTER,
        fontName='Helvetica'
    )
    
    # Section header style
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#1e3a8a'),
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    # Disease name style
    disease_style = ParagraphStyle(
        'DiseaseName',
        parent=styles['Heading3'],
        fontSize=13,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=6,
        spaceBefore=10,
        fontName='Helvetica-Bold'
    )
    
    # Body text style
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#475569'),
        spaceAfter=6,
        alignment=TA_JUSTIFY,
        fontName='Helvetica',
        leading=14
    )
    
    # Add header
    story.append(Paragraph("ClaraVision Health", title_style))
    story.append(Paragraph("AI-Powered Skin Condition Analysis Report", subtitle_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Add disclaimer box
    disclaimer_data = [[Paragraph(
        "<b>⚕️ Medical Disclaimer:</b> This report is generated by an AI diagnostic assistance tool and is NOT a substitute "
        "for professional medical diagnosis. This system is optimized for African skin tones and SADC region skin conditions. "
        "Always consult with qualified healthcare providers for proper diagnosis and treatment. This tool is intended for "
        "educational and screening purposes only.",
        ParagraphStyle('Disclaimer', parent=body_style, fontSize=9, textColor=colors.HexColor('#92400e'), backColor=colors.HexColor('#fef3c7'))
    )]]
    
    disclaimer_table = Table(disclaimer_data, colWidths=[6.5*inch])
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fef3c7')),
        ('BOX', (0, 0), (-1, -1), 2, colors.HexColor('#f59e0b')),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Add report metadata
    story.append(Paragraph("Report Information", section_style))
    metadata_data = [
        ["Report Date:", timestamp.strftime('%B %d, %Y at %I:%M %p')],
        ["Analysis System:", "ClaraVision Health v1.0"],
        ["Model:", "PrecisionHealth Skin Condition Classification"],
        ["Target Population:", "African skin tones (Fitzpatrick IV-VI)"]
    ]
    
    metadata_table = Table(metadata_data, colWidths=[2*inch, 4.5*inch])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f8fafc')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#1e293b')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(metadata_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Add analyzed image
    story.append(Paragraph("Analyzed Image", section_style))
    
    # Resize image to fit on page
    img_buffer = io.BytesIO()
    image.save(img_buffer, format='JPEG')
    img_buffer.seek(0)
    
    # Calculate dimensions to fit in 4x4 inch box
    img_width, img_height = image.size
    aspect = img_height / float(img_width)
    
    if aspect > 1:
        # Portrait
        display_height = 4*inch
        display_width = display_height / aspect
    else:
        # Landscape
        display_width = 4*inch
        display_height = display_width * aspect
    
    img = Image(img_buffer, width=display_width, height=display_height)
    img.hAlign = 'CENTER'
    story.append(img)
    story.append(Spacer(1, 0.3*inch))
    
    # Add analysis results
    story.append(Paragraph("Analysis Results", section_style))
    
    if 'predictions' in results and len(results['predictions']) > 0:
        predictions = sorted(results['predictions'], key=lambda x: x.get('confidence', 0), reverse=True)
        
        # Summary table
        summary_data = [["Condition", "Confidence Level", "Confidence %"]]
        
        for pred in predictions:
            confidence = pred.get('confidence', 0) * 100
            class_name = pred.get('class', 'Unknown')
            
            if confidence >= 70:
                conf_label = "High"
                color = colors.HexColor('#dcfce7')
            elif confidence >= 40:
                conf_label = "Medium"
                color = colors.HexColor('#fef3c7')
            else:
                conf_label = "Low"
                color = colors.HexColor('#fee2e2')
            
            summary_data.append([class_name, conf_label, f"{confidence:.1f}%"])
        
        summary_table = Table(summary_data, colWidths=[3*inch, 1.75*inch, 1.75*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e3a8a')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Detailed findings for each condition
        story.append(PageBreak())
        story.append(Paragraph("Detailed Findings", section_style))
        story.append(Spacer(1, 0.1*inch))
        
        for idx, pred in enumerate(predictions):
            confidence = pred.get('confidence', 0) * 100
            class_name = pred.get('class', 'Unknown')
            
            # Only include high and medium confidence predictions in detail
            if confidence < 40:
                continue
            
            story.append(Paragraph(f"{idx + 1}. {class_name}", disease_style))
            story.append(Paragraph(f"<b>Confidence:</b> {confidence:.1f}%", body_style))
            
            disease_info = get_disease_info(class_name)
            
            if disease_info:
                
                # Description
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph("<b>Description:</b>", body_style))
                story.append(Paragraph(disease_info['description'], body_style))
                
                # Symptoms
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph("<b>Common Symptoms:</b>", body_style))
                for symptom in disease_info['symptoms']:
                    story.append(Paragraph(f"• {symptom}", body_style))
                
                # Treatment
                if include_treatment:
                    story.append(Spacer(1, 0.1*inch))
                    story.append(Paragraph("<b>Treatment Recommendations:</b>", body_style))
                    for treatment in disease_info['treatment']:
                        story.append(Paragraph(f"• {treatment}", body_style))
                
                # Prevention
                if include_prevention and 'prevention' in disease_info:
                    story.append(Spacer(1, 0.1*inch))
                    story.append(Paragraph("<b>Prevention Tips:</b>", body_style))
                    for tip in disease_info['prevention']:
                        story.append(Paragraph(f"• {tip}", body_style))
                
                # When to seek care
                if include_when_to_seek_care and 'when_to_seek_care' in disease_info:
                    story.append(Spacer(1, 0.1*inch))
                    story.append(Paragraph("<b>⚠️ When to Seek Medical Care:</b>", 
                        ParagraphStyle('Warning', parent=body_style, textColor=colors.HexColor('#dc2626'), fontName='Helvetica-Bold')))
                    for item in disease_info['when_to_seek_care']:
                        story.append(Paragraph(f"• {item}", body_style))
            
            if idx < len(predictions) - 1:
                story.append(Spacer(1, 0.2*inch))
                story.append(Paragraph("—" * 50, body_style))
                story.append(Spacer(1, 0.2*inch))
    else:
        story.append(Paragraph("No predictions were generated for this image.", body_style))
    
    # Add footer information
    story.append(PageBreak())
    story.append(Paragraph("Important Information", section_style))
    
    footer_text = """
    <b>Next Steps:</b><br/>
    1. Share this report with your healthcare provider for professional evaluation<br/>
    2. Do not self-diagnose or self-treat based solely on this AI analysis<br/>
    3. Seek immediate medical attention if experiencing severe symptoms<br/>
    4. Follow up with a dermatologist for definitive diagnosis and treatment plan<br/><br/>
    
    <b>About ClaraVision Health:</b><br/>
    ClaraVision Health is an AI-powered diagnostic assistance platform optimized for African skin tones and 
    common skin conditions in the SADC region. Our mission is to democratize access to dermatological expertise 
    across Africa by providing preliminary screening tools for healthcare facilities.<br/><br/>
    
    <b>Regulatory Status:</b> Demonstration/Proof of Concept<br/>
    <b>Planned Certifications:</b> MCAZ Registration, ISO 13485, CE Marking<br/><br/>
    
    <b>Contact Information:</b><br/>
    ClaraVision Health | Harare, Zimbabwe | SADC Region<br/>
    Entity: Estonia OÜ (for EU grant access)<br/><br/>
    
    <i>This report was generated on {timestamp} by ClaraVision Health v1.0</i>
    """.format(timestamp=timestamp.strftime('%B %d, %Y at %I:%M %p'))
    
    story.append(Paragraph(footer_text, body_style))
    
    # Build PDF
    doc.build(story)
    
    return filepath


def send_email_report(email_address, results, image, timestamp, include_treatment=True, include_prevention=True, include_when_to_seek_care=True):
    """
    Send the analysis report via email
    
    Args:
        email_address: Recipient email address
        results: API response from Roboflow
        image: PIL Image object
        timestamp: datetime object
        include_treatment: bool
        include_prevention: bool
        include_when_to_seek_care: bool
    
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    
    # Check for SMTP configuration in environment variables
    smtp_server = os.environ.get('SMTP_SERVER')
    smtp_port = os.environ.get('SMTP_PORT', '587')
    smtp_username = os.environ.get('SMTP_USERNAME')
    smtp_password = os.environ.get('SMTP_PASSWORD')
    sender_email = os.environ.get('SENDER_EMAIL', 'noreply@claravision.health')
    
    if not all([smtp_server, smtp_username, smtp_password]):
        # Return False if SMTP is not configured
        # In production, you would configure these via environment variables
        return False
    
    try:
        # Generate PDF report
        pdf_path = generate_pdf_report(results, image, timestamp, include_treatment, include_prevention, include_when_to_seek_care)
        
        # Create message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = email_address
        msg['Subject'] = f"ClaraVision Health - Skin Analysis Report ({timestamp.strftime('%Y-%m-%d')})"
        
        # Email body
        body = f"""
Dear Healthcare Professional,

Please find attached your ClaraVision Health skin condition analysis report generated on {timestamp.strftime('%B %d, %Y at %I:%M %p')}.

This AI-powered analysis is designed to assist in preliminary screening and should be reviewed by a qualified healthcare provider for professional diagnosis and treatment planning.

IMPORTANT REMINDER:
- This report is for educational and screening purposes only
- Always consult with qualified healthcare providers for proper diagnosis
- Do not use this report as a substitute for professional medical advice

About ClaraVision Health:
ClaraVision Health leverages advanced AI to provide skin condition analysis optimized for African skin tones and common conditions in the SADC region.

If you have any questions or need assistance, please contact our support team.

Best regards,
ClaraVision Health Team
Harare, Zimbabwe | SADC Region

---
This is an automated message. Please do not reply to this email.
        """
        
        msg.attach(MIMEText(body, 'plain'))
        
        # Attach PDF
        with open(pdf_path, 'rb') as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
        
        encoders.encode_base64(part)
        part.add_header(
            'Content-Disposition',
            f'attachment; filename= {os.path.basename(pdf_path)}',
        )
        msg.attach(part)
        
        # Send email
        with smtplib.SMTP(smtp_server, int(smtp_port)) as server:
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.send_message(msg)
        
        # Clean up PDF file
        os.remove(pdf_path)
        
        return True
        
    except Exception as e:
        print(f"Error sending email: {str(e)}")
        return False
